version: '3.8'

services:
  app:
    build: 
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=postgres
      - DB_NAME=kenya
      - DB_USER=postgres
      - DB_PASSWORD=Floridah2025!
      - APP_ENV=production
    depends_on:
      - postgres
    volumes:
      - ../../memory:/app/memory
      - ../../embeddings:/app/embeddings
      - ../../logs:/app/logs
      - ../../reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kenya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Floridah2025!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../data/schemas:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
